### ISSUE TITLE
API: /housing

### ISSUE THREAD

**Issue by joeoneil** [joeoneil/conditional-backend#8]
Housing view / maintenance routes
**6 Routes**

---

**GET** /points/{user}
_accessible to all members_

Gets a user's current housing points

---

**GET** /room/{user}
_accessible to all members_

Gets a user's current room

---

**GET** /room
_accessible to all members_

Gets all rooms on floor, and the users who live in them

---

**PUT** /room
_accessible to evals director_

Updates who lives in each room

---

**GET** /queue
_acessible to all users_

Gets the current housing queue information

---

**PUT** /queue
_accessible to evals director_

Modifies the current housing queue

**Comment by Qelxiros** [comment]
This is beyond the scope of this service.
